version: "3.9"

services:
  csvserver:
    image: infracloudio/csvserver:latest
     # Ensures compatibility with your arm64 host
    container_name: csvserver
    ports:
      - "9393:9300"
    env_file:
      - ./csvserver.env  # Explicitly load the .env file
    volumes:
      - ${PWD}/inputData:/csvserver/inputdata  # Mount the inputData directory correctly